apiVersion: apps/v1
kind: Deployment
metadata:
  name: adhd-planner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adhd-planner
  template:
    metadata:
      labels:
        app: adhd-planner
    spec:
      containers:
      - name: flask-app
        image: adhd-planner:latest
        ports:
        - containerPort: 5000